# model parameters
modelName: DNN

# algorithm parameters
algorithm: PGD
lr: 0.01
momentum: 0.1
criterion:  LogisticLoss

MisLabeledNoise: 0

noise: 0

# is input features
inputSize: 2

width: 
  - 3 
  - 4
  - 5
  - 6
deep: 
  - 3 

outputSize: 1
tau: 1

# dataset parameters
batchSize: 16
trainSamples:
  - 500
  - 1000
  - 3000
  - 5000
  - 7000
  - 9000
  - 12000
  - 15000
  - 18000
  - 21000
  - 23000
  - 26000

testSamples: 100
datasetSeed: 3
loaderName: makeMoon

# parameters in main
epochs: 200

# print parameters
interval: 2000
file: rename

epsilon: 1
alpha:
  - 0.05
  - 0.2
  - 0.4
  - 0.6
  - 0.8

norm: inf
iterations: 5
# save
SaveModelName: False
device: cpu
