# model parameters
modelName: ResNet18

# algorithm parameters
algorithm: PGD
lr: 0.01
momentum: 0.1

criterion: FocalLoss

# LogisticLoss
# LogisticAndSigmoidLoss
lossScale:
  - 1
  - 2
  - 3
  - 4
  - 5
# - 0

MisLabeledNoise: 0
#   - 0
#   - 0.08
#   - 0.16
#   - 0.24
#   - 0.32
#   - 0.40

noise: 0

width: 0

deep: 0

# is input features
inputSize: 2

outputSize: 1
tau: 1

# dataset parameters
batchSize: 32
trainSamples: 100

testSamples: 100
datasetSeed: 3
loaderName: CatAndDog

# parameters in main
epochs: 200

# print parameters
interval: 2000
file: rename

# adversarial training parameters
epsilon: 
  - 0.01
  - 0.02
  - 0.04
  - 0.06
  - 0.08

alpha: 0.01
  # - 0.0
  # - 0.0002
  # - 0.0004
  # - 0.0006
  # - 0.0008
  # - 0.001
  # - 0.002
  # - 0.004
  # - 0.006
  # - 0.008
  # - 0.01
  # - 0.02
  # - 0.04
  # - 0.06
  # - 0.08
  # - 0.1


norm: inf
iterations: 5

# save
SaveModelName: False
device: cuda
