# model parameters
modelName: ResNet18

# algorithm parameters
algorithm: PGD
lr: 0.01
momentum: 0.1

criterion: LogisticLoss

# LogisticLoss
# LogisticAndSigmoidLoss
# lossScale:
#   - 0.2
#   - 0.4
#   - 0.6
#   - 0.8
#   - 1
#   - 2
#   - 4


MisLabeledNoise: 0
#   - 0
#   - 0.08
#   - 0.16
#   - 0.24
#   - 0.32
#   - 0.40

noise: 0

width: 0

deep: 0

# is input features
inputSize: 2

outputSize: 1
tau: 1

# dataset parameters
batchSize: 32
trainSamples: 100

testSamples: 100
datasetSeed: 3
loaderName: CatAndDog

# parameters in main
epochs: 200

# print parameters
interval: 2000
file: rename

# adversarial training parameters
epsilon: 1
# 0.5
alpha:
  - 0.2
  - 0.4
  - 0.6
  - 0.8
#  - 0.0001
#  - 0.001
  # - 0.003
  # - 0.005
  # - 0.008
#  - 0.01
  # - 0.03
  # - 0.05
  # - 0.08
#  - 0.1
#  - 0.25
  # - 0.5
  # - 0.8
  # - 1.0

norm: inf
iterations: 5

# save
SaveModelName: False
device: cuda
