# model parameters
modelName: DNN

# algorithm parameters
algorithm: ERM
lr: 0.01
momentum: 0.1
criterion: LogisticLoss

MisLabeledNoise: 0

noise: 0

# is input features
inputSize: 30

width:
  - 35

deep: 
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

outputSize: 1
tau: 1

# dataset parameters
batchSize: 16
trainSamples: 1000
testSamples: 100
datasetSeed: 3
loaderName: breastCancer

# parameters in main
epochs: 200

# print parameters
interval: 2000
file: rename

# save
SaveModelName: False
device: cpu
