# model parameters
modelName: ResNet18

# algorithm parameters
algorithm: ERM
lr: 0.01
momentum: 0.1
  # - LogisticAndWelschLoss
  # - LogisticAndSavageLoss
criterion: 
  # - LogisticLoss
  - LogisticAndSigmoidLoss
  
  # - 0.50
  # - 0.52
  # - 0.54
MisLabeledNoise:
  - 0.56

noise: 0

width: 0

deep: 0

# is input features
inputSize: 2

outputSize: 1
tau: 1

# dataset parameters
batchSize: 16
trainSamples: 100

testSamples: 100
datasetSeed: 3
loaderName: CatAndDog

# parameters in main
epochs: 200

# print parameters
interval: 2000
file: rename

# save
SaveModelName: False
device: cuda
